events {
    worker_connections 1024;
}

http {
    include /opt/homebrew/etc/nginx/mime.types; #include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 0.0.0.0:8888;
        server_name _;

        # 前端静态文件
        location / {
            root /Users/zec/Repo/ecs-beginner/frontend; #root /root/ecs-beginner/ecs-beginner/frontend;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # 后端 API 代理
        location /api/ {
            proxy_pass http://127.0.0.1:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
